name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag csi-rclone
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
    - name: Tag on registry
      run: docker tag csi-rclone ${{ secrets.REGISTRY }}
    - name: Push image to DO Container Registry 
      run: docker push ${{ secrets.REGISTRY }}
